package mx.edu.uttt.view;

/**
 *
 * @author USER01
 */
public class frmLogin extends javax.swing.JFrame {

    /**
     * Creates new form frmLogin
     */
    public frmLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTitulo = new javax.swing.JPanel();
        etTitulo = new javax.swing.JLabel();
        pnlAccion = new javax.swing.JPanel();
        etNombreUsuario = new javax.swing.JLabel();
        etPassword = new javax.swing.JLabel();
        txtNombreUsuario = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        BtnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        pnlTitulo.setBackground(new java.awt.Color(255, 255, 255));
        pnlTitulo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlTitulo.setLayout(null);

        etTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        etTitulo.setForeground(new java.awt.Color(0, 153, 204));
        etTitulo.setText("Bienvenidos, Sistema de Acceso a Usuarios");
        pnlTitulo.add(etTitulo);
        etTitulo.setBounds(60, 20, 300, 30);

        getContentPane().add(pnlTitulo);
        pnlTitulo.setBounds(0, 0, 432, 60);

        pnlAccion.setBackground(new java.awt.Color(204, 204, 255));
        pnlAccion.setLayout(null);

        etNombreUsuario.setText("Nombre de Usuario:");
        pnlAccion.add(etNombreUsuario);
        etNombreUsuario.setBounds(40, 30, 120, 20);

        etPassword.setText("Password:");
        pnlAccion.add(etPassword);
        etPassword.setBounds(40, 60, 100, 30);
        pnlAccion.add(txtNombreUsuario);
        txtNombreUsuario.setBounds(170, 30, 240, 20);
        pnlAccion.add(txtPassword);
        txtPassword.setBounds(170, 60, 240, 20);

        BtnLogin.setBackground(new java.awt.Color(255, 255, 255));
        BtnLogin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnLogin.setForeground(new java.awt.Color(0, 153, 204));
        BtnLogin.setText("Login");
        pnlAccion.add(BtnLogin);
        BtnLogin.setBounds(340, 90, 73, 23);

        getContentPane().add(pnlAccion);
        pnlAccion.setBounds(0, 60, 430, 140);

        setBounds(0, 0, 448, 239);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnLogin;
    private javax.swing.JLabel etNombreUsuario;
    private javax.swing.JLabel etPassword;
    private javax.swing.JLabel etTitulo;
    private javax.swing.JPanel pnlAccion;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JTextField txtNombreUsuario;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
